version: '3'

services:

  postgres:
    image: "postgres:12"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: beach_product

volumes:
  db_data:
